### ISSUE TITLE
Error 500 - Internal Server Error 

### ISSUE THREAD

**Issue by parimaay** [SAP/hcpms-xso-high-volume-toolkit#1]
Hey there, 
would you please help me out with this issue:

When I try to execute delta.xsjs service, it gives me error of 500 Internal Server Error, with additional info below:

Error: HttpClient.getResponse: Can't get the response from the server: internal error occurred "Connection to [xxx] lost while reading response." (line 104 position 1 in /sap/odata/util/lib/transfer/client/client.xsjslib)
[14190]{303828}[-1/-1] 2017-06-13 14:58:04.143541 e IpConnection     IPConnection.cpp(00248) : comm::read failed with rc = 15 | 
[14190]{303828}[-1/-1] 2017-06-13 14:58:04.143568 e HttpClient       HttpClient.cpp(00401) : 68: Connection to [xxx] lost while reading response.
[14190]{303828}[-1/-1] 2017-06-13 14:58:04.143739 e xsa:com.example. SandBox.cpp(01481) : Found the following errors:

**Comment by miffels** [comment]
Hi @parimaay,

Sorry, apparently I have not received a notification about this issue. I am sorry to say that I cannot see any issues in the log, other than that appears to be an issue with the upstream host. I would recommend enabling INFO-level logging for your application in ``/sap/hana/ide/trace/``, which will enable the library to log all the requests it is performing, including some of the payload. Then you can replay the request and see what the issue between the library and the system is.

Since unfortunately a lot of time has passed since you opened the request, I am closing this issue. Please reopen it if there are still problems.
